### ISSUE TITLE
Missed some files while concatenating files in microbiome data

### ISSUE THREAD

**Issue by kirtanp** [jmuth/ADA_homeworks#1]
While concatenating the list of files you are skipping the first two files ( I guess you want to skip `MID1` and `metadata` )

```
for file in files[2:]:
    mid = importMid(file)
    midAll = pd.concat([midAll, mid], axis=0)
```

Perhaps you forgot that you had already removed the first two elements of `files`  by doing `

```
files.remove('MID1.xls')
files.remove('metadata.xls')
```

So your final result is missing some of entries. Correct me if I am wrong. :)

**Comment by glederrey** [comment]
Mmmmhhh... You're right.. What a stupid mistake.. -.-'' 
Thanks! We will correct that after the end of the peer reviewing..
